### ISSUE TITLE
Linkificator doesn't work anymore…

### ISSUE THREAD

**Issue by Der-Dings** [MarkaPola/Linkificator#10]
since the Update to 3.3.0

All settings on standard. These are just two sites, others don't work either:

https://www.heise.de/forum/heise-online/News-Kommentare/Umstieg-auf-Open-Source-Schleswig-Holstein-will-sich-von-Microsoft-loesen/Re-Wieso-nicht-eine-einheitliche-Loesung-nutzen/posting-32542628/show/?seite=all

https://forum.golem.de/kommentare/wissenschaft/elektromobiltaet-ups-kauft-1.000-elektrolieferwagen-von-workhorse/solange-die-nicht-anfangen-zu-brennen.../118628,5117129,5117129,read.html#msg-5117129

Or is it just me? (Actually needless to mention, but still: before the update Linkificator worked on these pages).

**Comment by Der-Dings** [comment]
Maybe it is me. It works on this page:

https://www.heise.de/forum/heise-online/News-Kommentare/Umstieg-auf-Open-Source-Schleswig-Holstein-will-sich-von-Microsoft-loesen/Re-Es-gibt-auch-noch-Menschen-die-nachdenken-ohne-Microsoft-Lobby-Typen/posting-32538251/show/?seite=all

Still strange – why does the heise.de forum work in one case, but not in the other? Therefore I leave that issue open, maybe the author can say something (and, if necessary, let it flow into the development).

**Comment by d4k0** [comment]
Same problem here. It seems that Linkificator doesn't get loaded as I also don't get the context menu for it. The new shortcuts don't have any effect, either.

**Comment by MarkaPola** [comment]
For an unknown reason, the latest update breaks the add-on.
To solve the issue, uninstall and reinstall Linkificator.  May-be restarting Firefox before re-installation is a good idea...

**Comment by d4k0** [comment]
Restarting Firefox didn't work, but reinstalling the add-on did the trick.

**Comment by mipani** [comment]
Had the same issue. Uninstalling Linkifikator, restarting Firefox and installing Linkifikator again did it for me too.

**Comment by Der-Dings** [comment]
OK, now I am **really** confused. Today, without changing anything, both examples I posted before… worked! I have absolutely no idea what's going on ¯\_(ツ)_/¯

**Comment by Der-Dings** [comment]
I did nothing more than switch the computer off in the evening and on again the next morning - and *bam* is the error gone. It seems to be similar with the others, see above.

Since the error, for whatever reason, no longer occurs, I will close this case now.
