### ISSUE TITLE
[Question] Latest update requires access to all websites

### ISSUE THREAD

**Issue by aeisenberg** [MarkaPola/Linkificator#11]
I appreciate the work that you have done with Linkificator, but I see that the latest version now requires access to all of my website data. Can you explain the reason for this?

**Comment by MarkaPola** [comment]
Permissions had not changed from previous version. Access to all web sites was required from the beginning.

Firefox request agreement for access to all sites because I fix a syntax error in URL pattern in manifest file and Firefox consider this as a change in the rules regarding web sites.

**Comment by aeisenberg** [comment]
Thanks for the explanation.
