### ISSUE TITLE
Paypal can't login

### ISSUE THREAD

**Issue by MysteryIII** [MarkaPola/Linkificator#17]
There seems to be an issue with the Paypal login page. As long as Linkificator is active, I can't log in, even though it shows that no links are processed. Once I blacklist paypal, I can log in without any problems.

**Comment by MarkaPola** [comment]
Hi,

My quick test show me two things:

- On initial login step (i.e. without any cookie), the login is done in two pages:
  1. Enter your e-mail  on the first page
  2. Enter your password. Here Linkificator shows one link processed. Above the input box for password, your e-mail login is displayed and Linkificator had processed this URI. And it is not possible to successfully login.
- On next logins, both inputs fields are displayed on the same with e-mail already filled. Here the Linkificator coins is zero.

So, even if the count is zero, the page seems to update internally the contents by storing the e-mail as part of the page. Preventing this processing is not really possible. So your approach is the right one: add an entry in the black list.

FYI, it is not required to include all the domain as black list. You can specify only this page by specifying the following regular expression: **www.paypal.com/[^/]/signin**

**Comment by MysteryIII** [comment]
Thanks a lot. Added this exception.
